### ISSUE TITLE
SQLファイルについて

### ISSUE THREAD

**Issue by qeita** [chirip/08_42_Hashimoto_Yu#1]
@chirip 
お疲れ様です。G'sチューターのヤギです。  
課題提出お疲れ様でした。  
  
提出ファイルを拝見したところ、phpmyadminよりエクスポートされたSQLファイルが見当たらないような。。アップされてないようでしたら、お手数ですがご自身のPCで作ったDBのテーブルをphpmyadminからエクスポートし、そちらもアップしていただければとおもいます。

**Comment by chirip** [comment]
失礼しました。仕事が終わりましたら対応させて頂きます。
ご指摘ありがとうございます。

2018年2月2日 17:03 qeita <notifications@github.com>:

**Comment by chirip** [comment]
遅くなり申し訳ありません。先ほどphpmyadminのエクスポートデータを追加いたしました。
ご確認ください。

2018年2月2日 17:03 qeita <notifications@github.com>:

**Comment by qeita** [comment]
ご連絡ありがとうございますー。  
内容確認しインポートできましたので、こちらのissueクローズ致します!
